version: '3.3'
services:
  db:
    image: postgres
    ports:
      - "5433:5432"
    volumes:
      - "./database:/var/lib/postgresql/data"
    env_file:
      - .env

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - ../frontend/:/app/result_build/
  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/

    

